function [r100,r1000,r100u,r1000u] = main

load ('UFhet.mat');
nagents = [2 3];

options = dgmset();
options = dgmset(options, ...
                    'Swnk', swnk, ...
                    'Agents', uf , ...
                    'MediationType', 'dgm1', ...
                    'Ni', 100, ...
                    'Nsets', 10, ...
                    'Nexp', 10, ...
                    'SelectionThreshold', [], ...
                    'PopulationSize', 20, ...
                    'Plot', 'off', ...
                    'PlotFcn', {@plotrewardsfcn,@plotwinnercounterfcn});
                
quotatypes = {'fixed','fixed','dynamicquota','dynamicpopulationsize','dynamic','decay', ...
            'fixed','dynamicquota','dynamicpopulationsize','dynamic','decay', ...
            'fixed','dynamicquota','dynamicpopulationsize','dynamic','decay'};
agentypes = {'quotas','quotas','quotas','quotas','quotas','quotas', ...
             'rank','rank','rank','rank','rank', ...
             'truevoting','truevoting','truevoting','truevoting','truevoting'};
initialquotas = [15,5,10,10,10,15, ...
                    5,10,10,10,15, ...
                    5,10,10,10,15];
                
r100 = [];
options.Generations = 100;
for j=nagents
    
experiments = { ['heta' num2str(j) 'f15100'],['heta' num2str(j) 'f5100'],['heta' num2str(j) 'dynq100'], ...
                ['heta' num2str(j) 'dynp100'],['heta' num2str(j) 'dyn100'],['heta' num2str(j) 'dcy100'], ...
                ['heta' num2str(j) 'f5r100'],['heta' num2str(j) 'dynqr100'], ...
                ['heta' num2str(j) 'dynpr100'],['heta' num2str(j) 'dynr100'],['heta' num2str(j) 'dcyr100'], ...
                ['heta' num2str(j) 'f5t100'],['heta' num2str(j) 'dynqt100'], ...
                ['heta' num2str(j) 'dynpt100'],['heta' num2str(j) 'dynt100'],['heta' num2str(j) 'dcyt100']
                };
            
    for i=1:length(experiments)
        fprintf('\n%s',experiments{i});
        options = dgmset(options, ...
                        'Nag', j, ...
                        'QuotaType', quotatypes{i}, ...
                        'AgentType', agentypes{i}, ...
                        'InitialQuota', initialquotas(i));
                    state = negotiate(options);
                    save(experiments{i},'state');
                    r100 = [r100;state.Results.stats];
    end
end
save r100;
%r100 = [r100(1:16,:) r100(17:32,:) r100(33:48,:) r100(49:64,:) r100(65:80,:)];
%%%%%%%%
r1000 = [];
options.Generations = 1000;

for j=nagents
    
experiments = { ['heta' num2str(j) 'f151000'],['heta' num2str(j) 'f51000'],['heta' num2str(j) 'dynq1000'], ...
                ['heta' num2str(j) 'dynp1000'],['heta' num2str(j) 'dyn1000'],['heta' num2str(j) 'dcy1000'], ...
                ['heta' num2str(j) 'f5r1000'],['heta' num2str(j) 'dynqr1000'], ...
                ['heta' num2str(j) 'dynpr1000'],['heta' num2str(j) 'dynr1000'],['heta' num2str(j) 'dcyr1000'], ...
                ['heta' num2str(j) 'f5t1000'],['heta' num2str(j) 'dynqt1000'], ...
                ['heta' num2str(j) 'dynpt1000'],['heta' num2str(j) 'dynt1000'],['heta' num2str(j) 'dcyt1000']
                };

    for i=1:length(experiments)
        fprintf('\n%s',experiments{i});
        options = dgmset(options, ...
                        'Nag', j, ...
                        'QuotaType', quotatypes{i}, ...
                        'AgentType', agentypes{i}, ...
                        'InitialQuota', initialquotas(i));
                    state = negotiate(options);
                    save(experiments{i},'state');
                    r1000 = [r1000;state.Results.stats];
    end
end
save r1000;
nagents = [5 7 10];

                
r100u = [];
options.Generations = 100;
for j=nagents
    
experiments = { ['heta' num2str(j) 'f15100'],['heta' num2str(j) 'f5100'],['heta' num2str(j) 'dynq100'], ...
                ['heta' num2str(j) 'dynp100'],['heta' num2str(j) 'dyn100'],['heta' num2str(j) 'dcy100'], ...
                ['heta' num2str(j) 'f5r100'],['heta' num2str(j) 'dynqr100'], ...
                ['heta' num2str(j) 'dynpr100'],['heta' num2str(j) 'dynr100'],['heta' num2str(j) 'dcyr100'], ...
                ['heta' num2str(j) 'f5t100'],['heta' num2str(j) 'dynqt100'], ...
                ['heta' num2str(j) 'dynpt100'],['heta' num2str(j) 'dynt100'],['heta' num2str(j) 'dcyt100']
                };
            
    for i=1:length(experiments)
        fprintf('\n%s',experiments{i});
        options = dgmset(options, ...
                        'Nag', j, ...
                        'QuotaType', quotatypes{i}, ...
                        'AgentType', agentypes{i}, ...
                        'InitialQuota', initialquotas(i));
                    state = negotiate(options);
                    save(experiments{i},'state');
                    r100u = [r100u;state.Results.stats];
    end
end
save r100u;
%r100 = [r100(1:16,:) r100(17:32,:) r100(33:48,:) r100(49:64,:) r100(65:80,:)];
%%%%%%%%
r1000u = [];
options.Generations = 1000;

for j=nagents
    
experiments = { ['heta' num2str(j) 'f151000'],['heta' num2str(j) 'f51000'],['heta' num2str(j) 'dynq1000'], ...
                ['heta' num2str(j) 'dynp1000'],['heta' num2str(j) 'dyn1000'],['heta' num2str(j) 'dcy1000'], ...
                ['heta' num2str(j) 'f5r1000'],['heta' num2str(j) 'dynqr1000'], ...
                ['heta' num2str(j) 'dynpr1000'],['heta' num2str(j) 'dynr1000'],['heta' num2str(j) 'dcyr1000'], ...
                ['heta' num2str(j) 'f5t1000'],['heta' num2str(j) 'dynqt1000'], ...
                ['heta' num2str(j) 'dynpt1000'],['heta' num2str(j) 'dynt1000'],['heta' num2str(j) 'dcyt1000']
                };

    for i=1:length(experiments)
        fprintf('\n%s',experiments{i});
        options = dgmset(options, ...
                        'Nag', j, ...
                        'QuotaType', quotatypes{i}, ...
                        'AgentType', agentypes{i}, ...
                        'InitialQuota', initialquotas(i));
                    state = negotiate(options);
                    save(experiments{i},'state');
                    r1000u = [r1000u;state.Results.stats];
    end
end
save r1000u;
%r1000 = [r1000(1:16,:) r1000(17:32,:) r1000(33:48,:) r1000(49:64,:) r1000(65:80,:)];

% r = [];
% r(:,1:2:33) = r100;
% r(:,2:2:34) = r1000;
