d = [0 0;10 10];
sgB=sgr(2,...
    [30 30; 40 40],...
    d,...
    {@ft1,@ft1;...
    @ft1,@ft1;...
    },...
    {[] [];...
    [] [];...
    },...
    {@fu1,@fu1;...
    @fu2,@fu2;...
    },...
    {'media=1;desv=0.5;', 'media=1;desv=0.5;';...
    'media=1;desv=0.5;', 'media=1;desv=0.5;';...
    });


rB=rsgr(sgB,[0 100]);
%Normalización a 1 de las funciones de utilidad. El optimizador genético
%funciona mejor que los restantes.
% fB = @(x) -1*frsgr(x,rB,d);
% options = gaoptimset('PopulationSize', 100*length(d));
% [x, fvalB] = ga(fB, length(d), [], [], [], [], d(1,:), d(2,:), [], options);
% fvalB = abs(fvalB);
%fB = @(x,d) frsgr(x,rB,d)./fvalB;
fB = @(x,d) frsgr(x,rB,d);