function expectation = owafcn(x)
% OWA Aggregates Agents' preferences using quantifier Q generated by alfa
% parameter
    global ALFA;
    global S;
    global ST;
    global agents;
    global type;
    global WT;
    global quota;
        
    score = votingfcn(agents(x),type);
        
    [nr,na] = size(score);
    w = getowaweights(getquantifier(1.1,ALFA),na);
    expect = sort(score, 2, 'descend');
    expectation = sum(expect.*repmat(w,nr,1), 2);
    
    S = sort(expectation,'descend');
    S = max(S(1:quota));
    
    ST = sort(sum(expect.*repmat(WT,nr,1), 2),'descend');
    ST = max(ST(1:quota));
end